version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    networks:
      - api_network

networks:
    api_network:
        driver: bridge
